# Introduction



## Review of models
Feirman et al [-@Feirman2016;-@Feirman2017] and Berg at al [-@Berg2017] carried out recent reviews of smoking models from policy evaluation and health economics perspectives.  

A large proportion of models - especially those that take a health economics perspective - simulate the remaining lifetimes of a sample of individuals, modelling transitions among smoking states, and often also among disease states. The main models of this kind that have been used for the UK are the models that have been used to inform the [National Institute for Health and Care Excellence (NICE)](https://www.nice.org.uk/) guidance on smoking cessation. Building on previous model development [@Flack2007], version 1 of the NICE Tobacco Return on Investment (ROI) Tool [@Trapero-Bertran2011] is a discrete time state-transition 'Markov' model with three states: smoker, former smoker, dead. The health conditions considered are lung cancer, coronary heart disease, chronic obstructive pulmonary disease, myocardial infarction and stroke. It assumes a constant underlying background quit rate, that 2\% of smokers are assumed to quit each year through self-motivation, assisted or unassisted. The model allows the user to investigate the potential impact of providing behavioural support to smokers through various routes, of providing smokers with different types of Nicotine Replacement Therapy (NRT) and pharmacotherapies, and of population-level tobacco control policies such as mass media stop smoking campaigns. Intervention effects are typically evaluated based on their expected effects on the number of disease cases, the costs to the health service of treatment, and the change to quality-adjusted years of life lived. The NICE ROI tool has been developed in two ways: First, through the [EQUIPT project](http://equipt.eu/) the ROI modelling framework was extended to European countries [@Coyle2018]; Second, in the modelling to inform the NICE guidance 92 on stop smoking interventions and services [@Filby2018]. This structure of modelling is also used to evaluate the long-term effects of trial interventions e.g. in the recent trial of how giving e-cigarettes vs. NRT in stop smoking services affects quitting success [@Hajek2019].  

Another large proportion of models use their simulations of individual behaviour to predict evolving period trends at the population-level i.e. are IBPMs. To link between the individual-level (where trait trajectories over the remaining lifetimes of individuals are simulated) and population-level (where the continuing trends in the averages and distributions of traits are projected) requires the simulation of successive cohorts, so that at each time step outcomes can be estimated across all ages and subgroups in the population. However, not all IBPMs have a mathematical structure that makes this link exactly. Furthermore, IBPMs that do make this link can vary a great deal in how they inform the individual transition probabilities that generate the period trends at the population-level. The UK Health Forum developed a smoking IBPM that has been used to project smoking trends and to investigate the potential effects on smoking trends of policies such as raising the tax on tobacco products [@Bhimjiyani:2016aa;@Knuchel-Takano:2017aa;@Hunt:2018aa]. Song et al. [-@Song2019] developed a smoking IBPM that recapitulates the smoking prevalence in England from 2001--2016; they used this model to estimate the potential impact that stop smoking services had on trends in population smoking prevalence. Worldwide, there are a number of IBPMs that have similar capabilities (see [@Lhachimi2010]): the models that had most influence on the development of STPM were the RIVM-Chronic Disease Model (CDM) [@Hoogenveen:1998aa;@Hoogenveen:2008aa;@Hoogenveen2010], [Dynamo-HIA (DYNAmic MOdel for Health Impact Assessment)](https://www.dynamo-hia.eu/) [@Boshuizen2012], the Tobacco Policy Model [@Tengs2001;@Tengs2004], the modelling in the United States by Levy et al. [@Levy2002;@Levy2006;@Levy2010;@Levy2010a;@Levy2013;@Levy2016;@Tam2018] and by Warner and Mendez [@Mendez:1998aa;@Warner2012], and in New Zealand [@Deen2014] and Australia [@Gartner2009].  

Few, if any, smoking IBPMs use smoking transition probabilities that vary by age, sex and socio-economic conditions, that are time-varying between years, and that are estimated from data that follows individuals over time. This would likely be the ideal and most reliable evidence. In reality, each model has made use of the smoking data available for the region in question. For example, the RIVM-Chronic Disease Model estimates smoking transition probabilities directly from a particularly detailed survey that asks people about their current smoking status, about their smoking a year ago and, if they were a former smoker, when they had quit smoking [@Capannesi:2009aa]. Models also vary in how they conceptualise smoking transitions. The Dynamo-HIA model, for example, uses a method that estimates 'net transition probabilities' from a single-year of cross-sectional data, such that when the probabilities are applied, the prevalence of smoking remains constant between years [@VandeKassteele2012]. By contrast, a smoking IBPM in the United States estimates time-varying probabilities of smoking initiation and quitting from several years of cross-sectional data [@Holford:2014aa;@Tam2018]. Perhaps due to the difficulty of reliably estimating transition probabilities, a range of estimation methods have been applied. Few models use estimates that are stratified by individual characteristics such as socio-economic conditions, despite population-level evidence that smoking trends have varied greatly among strata.  

The conclusion that we drew from this review of smoking models is that our *a priori* conceptual and mathematical description of STPM may well have to be modified following consideration of how to reliably estimate the smoking transition probabilities that will inform it. The positive sign from previous models is that it could well be possible to use several years of cross-sectional data to estimate year- and age-specific probabilities of smoking initiation and quitting that are stratified by sex and socio-economic conditions. The next section looks in more detail at methods to infer smoking transition probabilities.  